<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>python on Alex Ptakhin</title>
    <link>https://aptakhin.name/tags/python/</link>
    <description>Recent content in python on Alex Ptakhin</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <lastBuildDate>Sun, 10 May 2020 00:00:00 +0000</lastBuildDate>
    
	<atom:link href="https://aptakhin.name/tags/python/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>[ru] Последний довод зависшего процесса</title>
      <link>https://aptakhin.name/posts/2020/last-in-debugging/</link>
      <pubDate>Sun, 10 May 2020 00:00:00 +0000</pubDate>
      
      <guid>https://aptakhin.name/posts/2020/last-in-debugging/</guid>
      <description>Симптомы. Один из подпроцессов в поде кубернетса просто вис и не логировал данные.
Заходим в поду.
Чтобы понять про процессы:
$ top top - 19:00:06 up 22 days, 10:42, 0 users, load average: 0.79, 0.89, 1.11 Tasks: 13 total, 1 running, 7 sleeping, 0 stopped, 5 zombie %Cpu(s): 1.2 us, 1.4 sy, 0.0 ni, 95.0 id, 2.1 wa, 0.2 hi, 0.1 si, 0.1 st MiB Mem : 32165.3 total, 14305.0 free, 3202.</description>
    </item>
    
  </channel>
</rss>